basePath: /public
definitions:
  domainBar:
    properties:
      Data:
        type: string
    type: object
  string:
    type: string
host: localhost:8080
info:
  contact:
    email: mail@mail.com
  description: Yo-ho-ho! API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Yo-ho-ho! swagger
  version: "1.0"
paths:
  /public/v1/bar/{key}:
    get:
      consumes:
      - application/json
      operationId: getpublicV1BarKey
      parameters:
      - description: key of object bar to return
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/domainBar'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/string'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/string'
      summary: Find object bar by key
      tags: []
schemes:
- http
swagger: "2.0"
